### ISSUE TITLE
ListRegisteredUsersController/List registered users

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/TaskMarket#221]
Behaviour: ListRegisteredUsersController/List registered users
Milestone: User management

Behaviour description:

This is the main behaviour for the service, so
* Make sure that the service interface matches the model
* If the service have return value, make sure that it is according to the specification
* Add any extras mentioned above

Annotations for the test cases:

    @TestedBehaviour("List registered users")
    @TestedService("ListRegisteredUsersController")

The production code is at com.kodekonveyor.market.register.ListRegisteredUsersController.java
The testbase is at com.kodekonveyor.market.register.ListRegisteredUsersControllerTestBase.java
The testcase is at com.kodekonveyor.market.register.ListRegisteredUsersControllerListRegisteredUsersTest.java

The service:
                
ListRegisteredUsersController
[![ListRegisteredUsersController](https://repository.kodekonveyor.com/TaskMarket/kode-konveyor/develop/pics/6e003d19-df10-4b08-a76b-5ada195f854a.png)](https://repository.kodekonveyor.com/TaskMarket/kode-konveyor/develop/index.html#6e003d19-df10-4b08-a76b-5ada195f854a)
    

How to work:
* identify what of the above is relevant to your service
* come up with a test about the relevant part
  * create a new empty test
  * make sure that the test description is understandable for the end user
  * put it to @DisplayName annotation for the test
  * write the test according to the test description
  * see the test fail in the right way
  * write the production code needed to pass the test, and no more
  * see the test pass
  * get rid of any PMD violations, comments and other problems in the code
  * see that all tests pass
* repeat until you covered all the relevant parts of the behaviour
* submit your pull request against the milestone of the task

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on [our discord channel](https://discord.gg/CkW6bvp) or ask your mentor.

**Comment by Mayuresh94** [comment]
grab
